interface Producto {
  id: number;
  nombre: string;
  precio: number | string;
  categoria: string;
}

export const productos: Producto[] = [
  { id: 1, nombre: "Aceite vegetal (1L)", precio: 2.5, categoria: "Abarrotes" },
  { id: 2, nombre: "Arroz (1kg)", precio: 1.5, categoria: "Abarrotes" },
  { id: 3, nombre: "Azúcar (1kg)", precio: 1.0, categoria: "Abarrotes" },
  { id: 4, nombre: "Café (250g)", precio: 3.0, categoria: "Abarrotes" },
  { id: 5, nombre: "Cereal (500g)", precio: 2.0, categoria: "Abarrotes" },
  { id: 6, nombre: "Fideos (500g)", precio: 1.5, categoria: "Abarrotes" },
  {
    id: 7,
    nombre: "Harina de trigo (1kg)",
    precio: 1.0,
    categoria: "Abarrotes",
  },
  { id: 8, nombre: "Leche (1L)", precio: 2.0, categoria: "Abarrotes" },
  { id: 9, nombre: "Sal (500g)", precio: 0.5, categoria: "Abarrotes" },
  {
    id: 10,
    nombre: "Atún enlatado (170g)",
    precio: 1.0,
    categoria: "Conservas",
  },
  {
    id: 11,
    nombre: "Frijoles enlatados (400g)",
    precio: 1.5,
    categoria: "Conservas",
  },
  {
    id: 12,
    nombre: "Garbanzos enlatados (400g)",
    precio: 1.5,
    categoria: "Conservas",
  },
  {
    id: 13,
    nombre: "Maíz enlatado (400g)",
    precio: 1.0,
    categoria: "Conservas",
  },
  {
    id: 14,
    nombre: "Sardinas enlatadas (170g)",
    precio: 1.0,
    categoria: "Conservas",
  },
  {
    id: 15,
    nombre: "Tomates enlatados (400g)",
    precio: 1.5,
    categoria: "Conservas",
  },
  { id: 16, nombre: "Aceitunas (350g)", precio: 2.0, categoria: "Encurtidos" },
  {
    id: 17,
    nombre: "Chiles jalapeños en vinagre (250g)",
    precio: 1.5,
    categoria: "Encurtidos",
  },
  {
    id: 18,
    nombre: "Pepinillos en vinagre (250g)",
    precio: 1.5,
    categoria: "Encurtidos",
  },
  {
    id: 19,
    nombre: "Manzanas (kg)",
    precio: 2.0,
    categoria: "Frutas y verduras",
  },
  {
    id: 20,
    nombre: "Bananas (kg)",
    precio: 1.05,
    categoria: "Frutas y verduras",
  },
  {
    id: 21,
    nombre: "Cebollas (kg)",
    precio: 1.15,
    categoria: "Frutas y verduras",
  },
  {
    id: 22,
    nombre: "Naranjas (kg)",
    precio: 0.1,
    categoria: "Frutas y verduras",
  },
  { id: 23, nombre: "Papas (kg)", precio: 1.5, categoria: "Frutas y verduras" },
  {
    id: 24,
    nombre: "Tomates (kg)",
    precio: 2.0,
    categoria: "Frutas y verduras",
  },
  { id: 25, nombre: "Docena de huevos", precio: 3.0, categoria: "Huevos" },
  {
    id: 26,
    nombre: "Carne molida de res (500g)",
    precio: 4.0,
    categoria: "Carnes",
  },
  { id: 27, nombre: "Pechuga de pollo (kg)", precio: 5.0, categoria: "Carnes" },
  {
    id: 28,
    nombre: "Aceite vegetal (1L)",
    precio: 2.5,
    categoria: "Abarrotes",
  },
  { id: 29, nombre: "Arroz (1kg)", precio: 1.5, categoria: "Abarrotes" },
  { id: 30, nombre: "Azúcar (1kg)", precio: 1.0, categoria: "Abarrotes" },
  {
    id: 31,
    nombre: "Galletas saladas (paquete)",
    precio: 2.3,
    categoria: "Abarrotes",
  },
  {
    id: 32,
    nombre: "Galletas dulces (paquete)",
    precio: 2.5,
    categoria: "Abarrotes",
  },
  {
    id: 33,
    nombre: "Galletas integrales (paquete)",
    precio: 2.8,
    categoria: "Abarrotes",
  },
  {
    id: 34,
    nombre: "Galletas con chocolate (paquete)",
    precio: 3.0,
    categoria: "Abarrotes",
  },
  {
    id: 35,
    nombre: "Papas fritas (bolsa)",
    precio: 2.2,
    categoria: "Abarrotes",
  },
  {
    id: 36,
    nombre: "Papas fritas sabor BBQ (bolsa)",
    precio: 2.4,
    categoria: "Abarrotes",
  },
  {
    id: 37,
    nombre: "Papas fritas sabor queso (bolsa)",
    precio: 2.5,
    categoria: "Abarrotes",
  },
  {
    id: 38,
    nombre: "Papas fritas sabor sal marina (bolsa)",
    precio: 2.3,
    categoria: "Abarrotes",
  },
  {
    id: 39,
    nombre: "Palomitas de maíz (bolsa)",
    precio: 1.8,
    categoria: "Abarrotes",
  },
  {
    id: 40,
    nombre: "Palomitas de maíz sabor mantequilla (bolsa)",
    precio: 2.0,
    categoria: "Abarrotes",
  },
  {
    id: 41,
    nombre: "Palomitas de maíz sabor caramelo (bolsa)",
    precio: 2.2,
    categoria: "Abarrotes",
  },
  {
    id: 42,
    nombre: "Palomitas de maíz sabor queso (bolsa)",
    precio: 2.1,
    categoria: "Abarrotes",
  },
  { id: 43, nombre: "Agua mineral (1L)", precio: 1.5, categoria: "Bebidas" },
  { id: 44, nombre: "Agua saborizada (1L)", precio: 2.0, categoria: "Bebidas" },
  {
    id: 45,
    nombre: "Refresco de cola (2L)",
    precio: 2.5,
    categoria: "Bebidas",
  },
  {
    id: 46,
    nombre: "Refresco de naranja (2L)",
    precio: 2.5,
    categoria: "Bebidas",
  },
  {
    id: 47,
    nombre: "Refresco de limón (2L)",
    precio: 2.5,
    categoria: "Bebidas",
  },
  { id: 48, nombre: "Jugos de frutas (1L)", precio: 2.8, categoria: "Bebidas" },
  {
    id: 49,
    nombre: "Detergente para ropa (1L)",
    precio: 3.5,
    categoria: "Productos de limpieza",
  },
  {
    id: 50,
    nombre: "Jabón de baño (unidad)",
    precio: 1.2,
    categoria: "Productos de limpieza",
  },
];
